### ISSUE TITLE
Listen for mentions in other message types

### ISSUE THREAD

**Issue by autophage** [radiosilence/wire#12]
If I have an @username in a comment to an event, it would be nice if that showed up as a "mention" for them.

**Comment by radiosilence** [comment]
Will definitely do this. Just need to standardise the comment/update models really, and then have updates posted on an event.

**Comment by radiosilence** [comment]
Could even give events "official" hashtags that would then show up on the page :)

**Comment by radiosilence** [comment]
Okay, I've pushed the @reply thing now.
