### ISSUE TITLE
"Edit Profile" page makes it look like you have to change your password to commit your changes

### ISSUE THREAD

**Issue by autophage** [radiosilence/wire#6]
While I was checking out the edit profile page, I noticed something funny about your UX: it sure looks like you HAVE to update your password if you want to change your avatar. You should have an "update password" option that doesn't look like if you change your profile pic and don't type in a new password then your password will be set to an empty string.

**Comment by radiosilence** [comment]
I've added text detailing that password would not be changed. Also there's a placeholder in the password field saying "No Change". Is that sufficient?

**Comment by autophage** [comment]
Much clearer now, thanks.
